### PR TITLE
Implement RFC 39: Change semantics of no-argument `m.Case()`.

### PR DESCRIPTION
**Pull request by wanda-phi**

### CODE REVIEW

**Review by whitequark — APPROVED** [review]
LGTM. Thank you!

**Comment by whitequark** [comment]
Do you think you could prepare a backport as well?

**Comment by wanda-phi** [comment]
I'm blocking the backport (or rather a different warning PR) on actually having a `v0.4.x` branch with the prereq commits (#1030 plus the ones already included in your backport PR) that I can use as a base

**Comment by whitequark** [comment]
Done: https://github.com/amaranth-lang/amaranth/pull/1029

**Comment by wanda-phi** [comment]
Still needs #1030

**Comment by whitequark** [comment]
Pushed that too

**Pull request merged**
