### PR TITLE
Implement RFC 27 amendment: deprecate `add_sync_process`, not `add_process`.

### PR DESCRIPTION
**Pull request by wanda-phi**

### CODE REVIEW

**Review by whitequark — CHANGES_REQUESTED** [review]
I think this is insufficient since we ban `yield Settle()` in `add_process`: https://amaranth-lang.org/rfcs/0027-simulator-testbenches.html#guidance-on-simulator-modalities

**Comment by wanda-phi** [comment]
> I think this is insufficient since we ban `yield Settle()` in `add_process`: https://amaranth-lang.org/rfcs/0027-simulator-testbenches.html#guidance-on-simulator-modalities

I don't quite understand? Using `Settle` in `add_process` raises a deprecation warning right on `Settle` construction.

**Comment by whitequark** [comment]
> I don't quite understand? Using `Settle` in `add_process` raises a deprecation warning right on `Settle` construction.

Oh sorry, I completely forgot that it's entirely deprecated, that's 100% on me.

**Review by whitequark — APPROVED** [review]
Thank you!

**Pull request merged**
