### PR TITLE
nmigen.sim._pyrtl: Add support for Assert/Assume

### LINKED ISSUE #427: Add support for Assert in simulation
Adding `Assert` support in pysim would be helpful for migrating LiteX code that relies on Display statements. While not equivalent to the Display statement, it would give enough information to figure out what's happening inside an elaboratable without exposing every single internal signal.

### PR DESCRIPTION
**Pull request by jeanthom**
Fixes #427 

TODO:
 * [ ] Ensure that I'm generating gen_test the right way
 * [ ] Improve the exception message?
 * [ ] Add unit tests
 * [ ] Fix VCD
 * [ ] Use a different exception

### CODE REVIEW

**Comment by jeanthom** [comment]
Should we have a separate exception type for simulation asserts?

**Comment by whitequark** [comment]
This looks generally reasonable, let's discuss the UI aspects on the next meeting.

**Comment by jeanthom** [comment]
Another issue I noticed:
```
/usr/lib64/python3.8/unittest/case.py:704: ResourceWarning: unclosed file <_io.TextIOWrapper name='test_soc_continuous_memtest.vcd' mode='wt' encoding='UTF-8'>
  outcome.errors.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback

======================================================================
FAIL: test_continuous_memtest (test_soc.SocTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jeanthomas/Documents/gram/gram/test/test_soc.py", line 223, in test_continuous_memtest
    runSimulation(soc, process, "test_soc_continuous_memtest.vcd")
  File "/home/jeanthomas/Documents/gram/gram/test/utils.py", line 25, in runSimulation
    sim.run()
  File "/home/jeanthomas/Documents/nmigen/nmigen/sim/pysim.py", line 382, in run
    while self.advance():
  File "/home/jeanthomas/Documents/nmigen/nmigen/sim/pysim.py", line 371, in advance
    self._real_step()
  File "/home/jeanthomas/Documents/nmigen/nmigen/sim/pysim.py", line 347, in _real_step
    process.run()
  File "<string>", line 987, in run
AssertionError: Assertion failed at /home/jeanthomas/Documents/gram/gram/phy/fakephy.py:328
```

The VCD file isn't closed properly. Not sure how we could fix this though.

**Comment by whitequark** [comment]
Thank you for submitting this pull request. We have iterated on the proposed design; as such, support for this feature has been accepted via [RFC 50](https://amaranth-lang.org/rfcs/0050-print.html) and implementation is tracked in issue #1186.

**Pull request closed without merging**
