### PR TITLE
[doc] tutorial : reference to my series of articles

### PR DESCRIPTION
**Pull request by sporniket**
I finally published a series of articles about how I set up things to work with Amaranth. I hope it is appropriate enough to put it here.

### CODE REVIEW

**Review by whitequark — APPROVED** [review]
Have you seen https://yowasp.org? Spares you from having to `make install` anything but openFPGALoader.

**Comment by sporniket** [comment]
I remember seeing that at one point, but failed to understand that it could be for me, and flushed it from my memory short after...

**Comment by whitequark** [comment]
```
pip install yowasp-yosys yowasp-nextpnr-ecp5
export YOSYS=yowasp-yosys
export NEXTPNR_ECP5=yowasp-nextpnr-ecp5
export ECPPACK=yowasp-ecppack
```

Now you have every bit of the toolchain except for openFPGALoader.

**Comment by sporniket** [comment]
I will have to test that and write an addendum...

**Pull request merged**
