### PR TITLE
Fixes #713 by always using latest version of Jinja2

### LINKED ISSUE #713: [amaranth-boards] Jinja2 dependency seems to require pinning of MarkupSafe dependency
After having looked [the raw logs of CI](https://pipelines.actions.githubusercontent.com/serviceHosts/514a3656-e17d-4829-9e26-0d12794b3619/_apis/pipelines/1/runs/259/signedlogcontent/2?urlExpires=2022-09-19T03%3A32%3A26.4017497Z&urlSigningMethod=HMACV1&urlSignature=jSEyzozlaeoTeSSI26fy2JFvw89st9D4ifa1iiTihBM%3D) for [my PR to amaranth-boards](https://github.com/amaranth-lang/amaranth-boards/pull/204), it seems that the jinja2 version used in amaranth relies on an old Markupsafe version (2.0.1), the newer ones (2.1+) have renamed some of their component (here `soft_unicode`).

Looking at github issues comments on [Jinja2](https://github.com/pallets/jinja/issues/1585#issuecomment-1043892628) and [Markupsafe](https://github.com/pallets/markupsafe/issues/282#issuecomment-1043899655), one is expected to either pin the markupsafe dependency, or update to latest jinja2.

```
2022-09-18T10:15:40.7447907Z ======================================================================
2022-09-18T10:15:40.7448394Z ERROR: pmod (unittest.loader._FailedTest)
2022-09-18T10:15:40.7449178Z ----------------------------------------------------------------------
2022-09-18T10:15:40.7449581Z ImportError: Failed to import test module: pmod
2022-09-18T10:15:40.7449907Z Traceback (most recent call last):
2022-09-18T10:15:40.7464918Z   File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
2022-09-18T10:15:40.7465404Z     module = __import__(module_name)
2022-09-18T10:15:40.7466121Z   File "/home/runner/work/amaranth-boards/amaranth-boards/amaranth_boards/extensions/pmod.py", line 3, in <module>
2022-09-18T10:15:40.7466535Z     from amaranth.build import *
2022-09-18T10:15:40.7467182Z   File "/home/runner/work/amaranth-boards/amaranth-boards/.eggs/amaranth-0.3-py3.10.egg/amaranth/build/__init__.py", line 3, in <module>
2022-09-18T10:15:40.7467587Z     from .plat import *
2022-09-18T10:15:40.7468207Z   File "/home/runner/work/amaranth-boards/amaranth-boards/.eggs/amaranth-0.3-py3.10.egg/amaranth/build/plat.py", line 6, in <module>
2022-09-18T10:15:40.7468792Z     import jinja2
2022-09-18T10:15:40.7469399Z   File "/home/runner/work/amaranth-boards/amaranth-boards/.eggs/Jinja2-2.11.3-py3.10.egg/jinja2/__init__.py", line 12, in <module>
2022-09-18T10:15:40.7470086Z     from .environment import Environment
2022-09-18T10:15:40.7470777Z   File "/home/runner/work/amaranth-boards/amaranth-boards/.eggs/Jinja2-2.11.3-py3.10.egg/jinja2/environment.py", line 25, in <module>
2022-09-18T10:15:40.7471247Z     from .defaults import BLOCK_END_STRING
2022-09-18T10:15:40.7471914Z   File "/home/runner/work/amaranth-boards/amaranth-boards/.eggs/Jinja2-2.11.3-py3.10.egg/jinja2/defaults.py", line 3, in <module>
2022-09-18T10:15:40.7472412Z     from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
2022-09-18T10:15:40.7473101Z   File "/home/runner/work/amaranth-boards/amaranth-boards/.eggs/Jinja2-2.11.3-py3.10.egg/jinja2/filters.py", line 13, in <module>
2022-09-18T10:15:40.7473762Z     from markupsafe import soft_unicode
2022-09-18T10:15:40.7474577Z ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/runner/work/amaranth-boards/amaranth-boards/.eggs/MarkupSafe-2.1.1-py3.10-linux-x86_64.egg/markupsafe/__init__.py)
```

### PR DESCRIPTION
**Pull request by sporniket**
(another experiment to see what break)

### CODE REVIEW

**Comment by sporniket** [comment]
This alternative breaks the same tests than #714

**Comment by sporniket** [comment]
List of broken tests : 

```
2022-09-20T04:52:28.1240730Z ======================================================================
2022-09-20T04:52:28.1241626Z FAIL: test_distance (tests.test_lib_coding.GrayCoderTestCase)
2022-09-20T04:52:28.1242468Z ----------------------------------------------------------------------
2022-09-20T04:52:28.1242833Z Traceback (most recent call last):
2022-09-20T04:52:28.1243565Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_coding.py", line 127, in test_distance
2022-09-20T04:52:28.1244118Z     self.assertFormal(spec, mode="prove")
2022-09-20T04:52:28.1244547Z   File "/home/runner/work/amaranth/amaranth/tests/utils.py", line 82, in assertFormal
2022-09-20T04:52:28.1244973Z     self.fail("Formal verification failed:\n" + stdout)
2022-09-20T04:52:28.1245335Z AssertionError: Formal verification failed:
2022-09-20T04:52:28.1245538Z 
2022-09-20T04:52:28.1245545Z 
2022-09-20T04:52:28.1245684Z ======================================================================
2022-09-20T04:52:28.1246038Z FAIL: test_reversible (tests.test_lib_coding.GrayCoderTestCase)
2022-09-20T04:52:28.1246588Z ----------------------------------------------------------------------
2022-09-20T04:52:28.1246963Z Traceback (most recent call last):
2022-09-20T04:52:28.1247608Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_coding.py", line 123, in test_reversible
2022-09-20T04:52:28.1248035Z     self.assertFormal(spec, mode="prove")
2022-09-20T04:52:28.1248474Z   File "/home/runner/work/amaranth/amaranth/tests/utils.py", line 82, in assertFormal
2022-09-20T04:52:28.1248890Z     self.fail("Formal verification failed:\n" + stdout)
2022-09-20T04:52:28.1249234Z AssertionError: Formal verification failed:
2022-09-20T04:52:28.1249435Z 
2022-09-20T04:52:28.1249443Z 
2022-09-20T04:52:28.1249914Z ======================================================================
2022-09-20T04:52:28.1250270Z FAIL: test_async (tests.test_lib_fifo.FIFOFormalCase)
2022-09-20T04:52:28.1250798Z ----------------------------------------------------------------------
2022-09-20T04:52:28.1251150Z Traceback (most recent call last):
2022-09-20T04:52:28.1251614Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_fifo.py", line 279, in test_async
2022-09-20T04:52:28.1252192Z     self.check_async_fifo(AsyncFIFO(width=8, depth=4))
2022-09-20T04:52:28.1252667Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_fifo.py", line 276, in check_async_fifo
2022-09-20T04:52:28.1253073Z     mode="hybrid", depth=fifo.depth * 4 + 1)
2022-09-20T04:52:28.1253501Z   File "/home/runner/work/amaranth/amaranth/tests/utils.py", line 82, in assertFormal
2022-09-20T04:52:28.1253915Z     self.fail("Formal verification failed:\n" + stdout)
2022-09-20T04:52:28.1254271Z AssertionError: Formal verification failed:
2022-09-20T04:52:28.1254457Z 
2022-09-20T04:52:28.1254465Z 
2022-09-20T04:52:28.1254603Z ======================================================================
2022-09-20T04:52:28.1254963Z FAIL: test_async_buffered (tests.test_lib_fifo.FIFOFormalCase)
2022-09-20T04:52:28.1255490Z ----------------------------------------------------------------------
2022-09-20T04:52:28.1255839Z Traceback (most recent call last):
2022-09-20T04:52:28.1256286Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_fifo.py", line 282, in test_async_buffered
2022-09-20T04:52:28.1256741Z     self.check_async_fifo(AsyncFIFOBuffered(width=8, depth=4))
2022-09-20T04:52:28.1257222Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_fifo.py", line 276, in check_async_fifo
2022-09-20T04:52:28.1257629Z     mode="hybrid", depth=fifo.depth * 4 + 1)
2022-09-20T04:52:28.1258041Z   File "/home/runner/work/amaranth/amaranth/tests/utils.py", line 82, in assertFormal
2022-09-20T04:52:28.1258449Z     self.fail("Formal verification failed:\n" + stdout)
2022-09-20T04:52:28.1258799Z AssertionError: Formal verification failed:
2022-09-20T04:52:28.1258996Z 
2022-09-20T04:52:28.1259004Z 
2022-09-20T04:52:28.1259140Z ======================================================================
2022-09-20T04:52:28.1259488Z FAIL: test_sync_buffered_pot (tests.test_lib_fifo.FIFOFormalCase)
2022-09-20T04:52:28.1260020Z ----------------------------------------------------------------------
2022-09-20T04:52:28.1260384Z Traceback (most recent call last):
2022-09-20T04:52:28.1260904Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_fifo.py", line 261, in test_sync_buffered_pot
2022-09-20T04:52:28.1261365Z     self.check_sync_fifo(SyncFIFOBuffered(width=8, depth=4))
2022-09-20T04:52:28.1261840Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_fifo.py", line 243, in check_sync_fifo
2022-09-20T04:52:28.1262224Z     mode="bmc", depth=fifo.depth + 1)
2022-09-20T04:52:28.1262633Z   File "/home/runner/work/amaranth/amaranth/tests/utils.py", line 82, in assertFormal
2022-09-20T04:52:28.1263045Z     self.fail("Formal verification failed:\n" + stdout)
2022-09-20T04:52:28.1263402Z AssertionError: Formal verification failed:
2022-09-20T04:52:28.1263603Z 
2022-09-20T04:52:28.1263610Z 
2022-09-20T04:52:28.1263749Z ======================================================================
2022-09-20T04:52:28.1264103Z FAIL: test_sync_buffered_potm1 (tests.test_lib_fifo.FIFOFormalCase)
2022-09-20T04:52:28.1264644Z ----------------------------------------------------------------------
2022-09-20T04:52:28.1265006Z Traceback (most recent call last):
2022-09-20T04:52:28.1265471Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_fifo.py", line 267, in test_sync_buffered_potm1
2022-09-20T04:52:28.1265908Z     self.check_sync_fifo(SyncFIFOBuffered(width=8, depth=3))
2022-09-20T04:52:28.1266378Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_fifo.py", line 243, in check_sync_fifo
2022-09-20T04:52:28.1266763Z     mode="bmc", depth=fifo.depth + 1)
2022-09-20T04:52:28.1267181Z   File "/home/runner/work/amaranth/amaranth/tests/utils.py", line 82, in assertFormal
2022-09-20T04:52:28.1267574Z     self.fail("Formal verification failed:\n" + stdout)
2022-09-20T04:52:28.1267929Z AssertionError: Formal verification failed:
2022-09-20T04:52:28.1268133Z 
2022-09-20T04:52:28.1268142Z 
2022-09-20T04:52:28.1268277Z ======================================================================
2022-09-20T04:52:28.1268710Z FAIL: test_sync_buffered_potp1 (tests.test_lib_fifo.FIFOFormalCase)
2022-09-20T04:52:28.1269230Z ----------------------------------------------------------------------
2022-09-20T04:52:28.1269593Z Traceback (most recent call last):
2022-09-20T04:52:28.1270047Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_fifo.py", line 264, in test_sync_buffered_potp1
2022-09-20T04:52:28.1270495Z     self.check_sync_fifo(SyncFIFOBuffered(width=8, depth=5))
2022-09-20T04:52:28.1270948Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_fifo.py", line 243, in check_sync_fifo
2022-09-20T04:52:28.1271337Z     mode="bmc", depth=fifo.depth + 1)
2022-09-20T04:52:28.1271755Z   File "/home/runner/work/amaranth/amaranth/tests/utils.py", line 82, in assertFormal
2022-09-20T04:52:28.1272271Z     self.fail("Formal verification failed:\n" + stdout)
2022-09-20T04:52:28.1272586Z AssertionError: Formal verification failed:
2022-09-20T04:52:28.1272769Z 
2022-09-20T04:52:28.1272777Z 
2022-09-20T04:52:28.1272905Z ======================================================================
2022-09-20T04:52:28.1273235Z FAIL: test_sync_fwft_npot (tests.test_lib_fifo.FIFOFormalCase)
2022-09-20T04:52:28.1273721Z ----------------------------------------------------------------------
2022-09-20T04:52:28.1274043Z Traceback (most recent call last):
2022-09-20T04:52:28.1274456Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_fifo.py", line 252, in test_sync_fwft_npot
2022-09-20T04:52:28.1274864Z     self.check_sync_fifo(SyncFIFO(width=8, depth=5, fwft=True))
2022-09-20T04:52:28.1275299Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_fifo.py", line 243, in check_sync_fifo
2022-09-20T04:52:28.1275643Z     mode="bmc", depth=fifo.depth + 1)
2022-09-20T04:52:28.1276028Z   File "/home/runner/work/amaranth/amaranth/tests/utils.py", line 82, in assertFormal
2022-09-20T04:52:28.1276411Z     self.fail("Formal verification failed:\n" + stdout)
2022-09-20T04:52:28.1276725Z AssertionError: Formal verification failed:
2022-09-20T04:52:28.1276913Z 
2022-09-20T04:52:28.1276920Z 
2022-09-20T04:52:28.1277045Z ======================================================================
2022-09-20T04:52:28.1277623Z FAIL: test_sync_fwft_pot (tests.test_lib_fifo.FIFOFormalCase)
2022-09-20T04:52:28.1278151Z ----------------------------------------------------------------------
2022-09-20T04:52:28.1278502Z Traceback (most recent call last):
2022-09-20T04:52:28.1278945Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_fifo.py", line 249, in test_sync_fwft_pot
2022-09-20T04:52:28.1279388Z     self.check_sync_fifo(SyncFIFO(width=8, depth=4, fwft=True))
2022-09-20T04:52:28.1279857Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_fifo.py", line 243, in check_sync_fifo
2022-09-20T04:52:28.1280227Z     mode="bmc", depth=fifo.depth + 1)
2022-09-20T04:52:28.1280647Z   File "/home/runner/work/amaranth/amaranth/tests/utils.py", line 82, in assertFormal
2022-09-20T04:52:28.1281058Z     self.fail("Formal verification failed:\n" + stdout)
2022-09-20T04:52:28.1281417Z AssertionError: Formal verification failed:
2022-09-20T04:52:28.1281618Z 
2022-09-20T04:52:28.1281625Z 
2022-09-20T04:52:28.1281748Z ======================================================================
2022-09-20T04:52:28.1282107Z FAIL: test_sync_not_fwft_npot (tests.test_lib_fifo.FIFOFormalCase)
2022-09-20T04:52:28.1282631Z ----------------------------------------------------------------------
2022-09-20T04:52:28.1282994Z Traceback (most recent call last):
2022-09-20T04:52:28.1283433Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_fifo.py", line 258, in test_sync_not_fwft_npot
2022-09-20T04:52:28.1283881Z     self.check_sync_fifo(SyncFIFO(width=8, depth=5, fwft=False))
2022-09-20T04:52:28.1284351Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_fifo.py", line 243, in check_sync_fifo
2022-09-20T04:52:28.1284735Z     mode="bmc", depth=fifo.depth + 1)
2022-09-20T04:52:28.1285133Z   File "/home/runner/work/amaranth/amaranth/tests/utils.py", line 82, in assertFormal
2022-09-20T04:52:28.1285606Z     self.fail("Formal verification failed:\n" + stdout)
2022-09-20T04:52:28.1285961Z AssertionError: Formal verification failed:
2022-09-20T04:52:28.1286163Z 
2022-09-20T04:52:28.1286171Z 
2022-09-20T04:52:28.1286307Z ======================================================================
2022-09-20T04:52:28.1286651Z FAIL: test_sync_not_fwft_pot (tests.test_lib_fifo.FIFOFormalCase)
2022-09-20T04:52:28.1287177Z ----------------------------------------------------------------------
2022-09-20T04:52:28.1287535Z Traceback (most recent call last):
2022-09-20T04:52:28.1287987Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_fifo.py", line 255, in test_sync_not_fwft_pot
2022-09-20T04:52:28.1288417Z     self.check_sync_fifo(SyncFIFO(width=8, depth=4, fwft=False))
2022-09-20T04:52:28.1288888Z   File "/home/runner/work/amaranth/amaranth/tests/test_lib_fifo.py", line 243, in check_sync_fifo
2022-09-20T04:52:28.1289277Z     mode="bmc", depth=fifo.depth + 1)
2022-09-20T04:52:28.1289831Z   File "/home/runner/work/amaranth/amaranth/tests/utils.py", line 82, in assertFormal
2022-09-20T04:52:28.1290226Z     self.fail("Formal verification failed:\n" + stdout)
2022-09-20T04:52:28.1290585Z AssertionError: Formal verification failed:
```

**Comment by whitequark** [comment]
Neither of these probably break any tests, it's an update to `yowasp-sby` that is incompatible with Python 3.7. The `main` branch is just as broken.

**Comment by whitequark** [comment]
See https://github.com/amaranth-lang/amaranth/issues/713#issuecomment-1256881764.

**Pull request closed without merging**
