### PR TITLE
tracer: add Python 3.11 support.

### PR DESCRIPTION
**Pull request by mwkmwkmwk**

### CODE REVIEW

**Review by whitequark — APPROVED** [review]
LGTM

**Comment by mwkmwkmwk** [comment]
It hasn't been released yet — I can try adding the beta version, but it'll likely have to be changed later

**Comment by whitequark** [comment]
It can be a non-required check for the beta version.

**Comment by mwkmwkmwk** [comment]
Just adding "3.11-dev" makes CI die on importlib-resources DeprecationWarning in certifi, which is a dependency of codecov.  I fixed it by unsetting `PYTHONWARNINGS` before running codecov (presumably no amaranth code actually gets run by that command, so we have no use for the warnings).

**Pull request merged**
