### PR TITLE
Implement RFC 46: Change `Shape.cast(range(1))` to `unsigned(0)`.

### PR DESCRIPTION
**Pull request by wanda-phi**
See amaranth-lang/rfcs#46.

### CODE REVIEW

**Review by whitequark — APPROVED** [review]
Thanks!

**Comment by whitequark** [comment]
Do we need any documentation changes here?

**Comment by wanda-phi** [comment]
> Do we need any documentation changes here?

Good question. I think the wording in lang reference could be somewhat stronger and say that it's not just "wide enough to represent any element", but is explicitly the minimal possible?

But mostly my feeling is that this was an implementation-documentation mismatch fix in the first place.

**Comment by whitequark** [comment]
> I think the wording in lang reference could be somewhat stronger and say that it's not just "wide enough to represent any element", but is explicitly the minimal possible?

I think that would be a good change to include here.

**Comment by wanda-phi** [comment]
Done.

**Review by whitequark — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
